const cfg = window.EP_CONFIG || {};
const brands = ["Hermès","Dior","Chanel","Louis Vuitton","YSL","Prada","Fendi","Gucci","Balenciaga","Celine","Miu Miu","Bottega Veneta","Goyard","Burberry","Loewe"];
const ready = cfg.SUPABASE_URL && cfg.SUPABASE_ANON_KEY && window.supabase;
const sb = ready ? window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY) : null;
const $ = id => document.getElementById(id);
let currentUser = null;
function msg(id,text){$(id).textContent=text||'';}
function fillBrands(){ $('brand').innerHTML = brands.map(b=>`<option value="${b}">${b}</option>`).join(''); }
async function init(){fillBrands(); if(!ready){msg('loginMsg','Supabase is not configured yet. Add your URL and anon key in config.js.'); return;} const {data}=await sb.auth.getSession(); if(data.session) await enter(data.session.user);}
async function enter(user){currentUser=user; if(cfg.ADMIN_EMAIL && user.email!==cfg.ADMIN_EMAIL){await sb.auth.signOut(); msg('loginMsg','This email is not allowed for admin access.'); return;} $('loginPanel').classList.add('hidden'); $('adminPanel').classList.remove('hidden'); $('logoutBtn').classList.remove('hidden'); await loadProducts();}
$('loginBtn').onclick = async ()=>{ if(!ready){msg('loginMsg','Supabase is not configured yet.'); return;} msg('loginMsg','Signing in...'); const {data,error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value}); if(error){msg('loginMsg',error.message);return;} await enter(data.user); };
$('logoutBtn').onclick = async ()=>{ if(sb) await sb.auth.signOut(); location.reload(); };
function clearForm(){['productId','name','nameAr','price','size','description','descriptionAr','images'].forEach(id=>$(id).value='');$('brand').value=brands[0];msg('formMsg','');}
$('clearBtn').onclick=clearForm;
$('productForm').onsubmit = async (e)=>{e.preventDefault(); if(!ready){msg('formMsg','Supabase is not configured.');return;} const payload={brand:$('brand').value,name:$('name').value.trim(),name_ar:$('nameAr').value.trim(),price:$('price').value.trim(),size:$('size').value.trim(),description:$('description').value.trim(),description_ar:$('descriptionAr').value.trim(),images:$('images').value.split('\n').map(x=>x.trim()).filter(Boolean),updated_at:new Date().toISOString()}; const id=$('productId').value; msg('formMsg','Saving...'); const res = id ? await sb.from('products').update(payload).eq('id',id) : await sb.from('products').insert({...payload,views:0}); if(res.error){msg('formMsg',res.error.message);return;} msg('formMsg','Saved.'); clearForm(); await loadProducts();};
async function loadProducts(){const {data,error}=await sb.from('products').select('*').order('created_at',{ascending:false}); if(error){$('adminProducts').innerHTML=`<p class="statusText">${error.message}</p>`;return;} $('adminProducts').innerHTML = (data||[]).map(p=>`<div class="adminRow"><div><strong>${p.name||'Untitled'}</strong><br><span class="muted">${p.brand||''} · ${p.price||''} · ${p.views||0} views</span></div><div class="rowActions"><button class="secondaryBtn" onclick='editProduct(${JSON.stringify(p).replace(/'/g,"&apos;")})'>Edit</button><button class="dangerBtn" onclick="deleteProduct('${p.id}')">Delete</button></div></div>`).join('') || '<p class="muted">No products yet.</p>';}
window.editProduct = (p)=>{ $('productId').value=p.id||''; $('brand').value=p.brand||brands[0]; $('name').value=p.name||''; $('nameAr').value=p.name_ar||''; $('price').value=p.price||''; $('size').value=p.size||''; $('description').value=p.description||''; $('descriptionAr').value=p.description_ar||''; $('images').value=Array.isArray(p.images)?p.images.join('\n'):(p.images||''); scrollTo({top:0,behavior:'smooth'}); };
window.deleteProduct = async (id)=>{ if(!confirm('Delete this product?')) return; const {error}=await sb.from('products').delete().eq('id',id); if(error){alert(error.message);return;} await loadProducts(); };
init();
