const BRANDS=['Hermès','Dior','Chanel','Louis Vuitton','YSL','Prada','Fendi','Gucci','Balenciaga','Celine','Miu Miu','Bottega Veneta','Goyard','Burberry','Loewe'];
const supabaseClient=supabase.createClient(window.EP_SUPABASE_URL,window.EP_SUPABASE_ANON_KEY);
const $=id=>document.getElementById(id);
$('brand').innerHTML=BRANDS.map(b=>`<option>${b}</option>`).join('');
function msg(id,t){$(id).textContent=t;}
async function check(){const {data}=await supabaseClient.auth.getSession();const logged=!!data.session;$('loginPanel').classList.toggle('hidden',logged);$('adminPanel').classList.toggle('hidden',!logged);$('logoutBtn').classList.toggle('hidden',!logged);if(logged)loadAdminProducts();}
$('loginBtn').onclick=async()=>{msg('loginMsg','Signing in...');const {error}=await supabaseClient.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});msg('loginMsg',error?error.message:'Logged in.');check();};
$('logoutBtn').onclick=async()=>{await supabaseClient.auth.signOut();check();};
async function uploadImages(files){const urls=[];for(const file of files){const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`products/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;const {error}=await supabaseClient.storage.from(window.EP_STORAGE_BUCKET).upload(path,file,{upsert:false});if(error)throw error;const {data}=supabaseClient.storage.from(window.EP_STORAGE_BUCKET).getPublicUrl(path);urls.push(data.publicUrl);}return urls;}
$('publishBtn').onclick=async()=>{try{msg('adminMsg','Uploading...');const images=await uploadImages($('images').files);const product={brand:$('brand').value,name:$('name').value.trim(),description:$('description').value.trim(),price:$('price').value.trim(),size:$('size').value.trim(),condition:$('condition').value.trim(),images,views:0};if(!product.name||!product.description||!product.price)throw new Error('Product name, description, and price are required.');const {error}=await supabaseClient.from('products').insert(product);if(error)throw error;msg('adminMsg','Product published to Supabase.');['name','description','price','size','condition','images'].forEach(id=>$(id).value='');loadAdminProducts();}catch(e){msg('adminMsg',e.message||'Could not publish product.');}};
async function loadAdminProducts(){const {data,error}=await supabaseClient.from('products').select('*').order('created_at',{ascending:false});if(error){$('adminProducts').innerHTML='<p class="muted">Could not load products.</p>';return;}$('adminProducts').innerHTML=(data||[]).map(p=>`<div class="admin-item"><img src="${(p.images&&p.images[0])||''}"><div><strong>${p.name||'Product'}</strong><br><span class="muted">${p.brand||''} · ${p.price||''} · Views: ${p.views||0}</span></div><button class="danger" data-id="${p.id}">Delete</button></div>`).join('')||'<p class="muted">No products added yet.</p>';$('adminProducts').querySelectorAll('.danger').forEach(btn=>btn.onclick=async()=>{if(confirm('Delete this product?')){await supabaseClient.from('products').delete().eq('id',btn.dataset.id);loadAdminProducts();}});}
check();
