const BRANDS=['Hermès','Dior','Chanel','Louis Vuitton','YSL','Prada','Fendi','Gucci','Balenciaga','Celine','Miu Miu','Bottega Veneta','Goyard','Burberry','Loewe'];
const supabaseClient=supabase.createClient(window.EP_SUPABASE_URL,window.EP_SUPABASE_ANON_KEY);
let currentBrand='All';
let slideState={};
const brandGrid=document.getElementById('brandGrid');
const productsEl=document.getElementById('products');
const emptyState=document.getElementById('emptyState');
const titleEl=document.getElementById('collectionTitle');
document.getElementById('floatingWa').href=`https://wa.me/${window.EP_WHATSAPP_NUMBER}`;
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function waLink(name){return `https://wa.me/${window.EP_WHATSAPP_NUMBER}?text=${encodeURIComponent('Hello, I would like to inquire about '+name)}`}
function renderBrands(){brandGrid.innerHTML=['All',...BRANDS].map(b=>`<button class="brand-btn" data-brand="${escapeHtml(b)}">${escapeHtml(b)}</button>`).join('');brandGrid.querySelectorAll('button').forEach(btn=>btn.onclick=()=>{currentBrand=btn.dataset.brand;loadProducts();location.hash='collection';});}
async function loadProducts(){titleEl.textContent=currentBrand==='All'?'Collection':currentBrand;let q=supabaseClient.from('products').select('*').order('created_at',{ascending:false});if(currentBrand!=='All')q=q.eq('brand',currentBrand);const {data,error}=await q;if(error){productsEl.innerHTML='';emptyState.textContent='Could not load products. Check Supabase table/policies.';emptyState.style.display='block';return;}renderProducts(data||[]);}
function getImages(p){if(Array.isArray(p.images)&&p.images.length)return p.images;if(p.image_url)return [p.image_url];return [];}
function renderProducts(items){emptyState.style.display=items.length?'none':'block';productsEl.innerHTML=items.map(p=>{const imgs=getImages(p);const idx=slideState[p.id]||0;const img=imgs[idx]||'';const name=p.name||p.product_name||'Product name';const desc=p.description||p.product_description||'';const price=p.price||'';return `<article class="product-card" data-id="${p.id}"><div class="image-wrap">${img?`<img class="product-image" src="${escapeHtml(img)}" alt="${escapeHtml(name)}">`:''}${imgs.length>1?`<button class="slide-btn slide-prev" data-dir="-1">‹</button><button class="slide-btn slide-next" data-dir="1">›</button><div class="dots">${imgs.map((_,i)=>`<span class="dot ${i===idx?'active':''}"></span>`).join('')}</div>`:''}</div><div class="product-info"><p class="product-brand">${escapeHtml(p.brand||'')}</p><h3>${escapeHtml(name)}</h3><p class="description">${escapeHtml(desc)}</p><p class="price">${escapeHtml(price)}</p><a class="whatsapp-btn" target="_blank" rel="noopener" href="${waLink(name)}">Inquire via WhatsApp</a></div></article>`}).join('');productsEl.querySelectorAll('.slide-btn').forEach(btn=>btn.onclick=e=>{const card=e.target.closest('.product-card');const p=items.find(x=>String(x.id)===String(card.dataset.id));const imgs=getImages(p);slideState[p.id]=((slideState[p.id]||0)+Number(btn.dataset.dir)+imgs.length)%imgs.length;renderProducts(items);});productsEl.querySelectorAll('.whatsapp-btn').forEach(a=>a.onclick=async()=>{const id=a.closest('.product-card').dataset.id;try{await supabaseClient.rpc('increment_product_views',{product_id:id});}catch(e){}})}
renderBrands();loadProducts();
