const cfg = window.EP_CONFIG || {};
const brands = ["Hermès","Dior","Chanel","Louis Vuitton","YSL","Prada","Fendi","Gucci","Balenciaga","Celine","Miu Miu","Bottega Veneta","Goyard","Burberry","Loewe"];
const brandAr = {"Hermès":"هيرميس","Dior":"ديور","Chanel":"شانيل","Louis Vuitton":"لويس فويتون","YSL":"سان لوران","Prada":"برادا","Fendi":"فندي","Gucci":"غوتشي","Balenciaga":"بالنسياغا","Celine":"سيلين","Miu Miu":"ميو ميو","Bottega Veneta":"بوتيغا فينيتا","Goyard":"غويارد","Burberry":"بربري","Loewe":"لويفي"};
const sampleProducts = brands.map((brand,i)=>({id:`sample-${i}`,brand,name:`${brand} Signature Selection`,name_ar:`${brandAr[brand]} مجموعة مختارة`,price:"Upon request",size:"Available on inquiry",description:"A curated placeholder product. Add your real products from the admin panel after Supabase is connected.",description_ar:"منتج تجريبي. أضيفي المنتجات الحقيقية من لوحة الإدارة بعد ربط Supabase.",images:[],views:0}));
const t = {en:{navHome:"Home",heroSub:"Curated luxury handbags",explore:"Explore Collection",eyebrow:"Explore by brand",brandTitle:"A curated selection from the world’s most celebrated maisons.",brandCopy:"Start from the homepage, choose a brand, then return here anytime to browse another maison.",backHome:"← Back to home",footerLine:"Curated Luxury Handbags",inquire:"Inquire via WhatsApp",noProducts:"No products published under this brand yet."},ar:{navHome:"الرئيسية",heroSub:"حقائب فاخرة مختارة بعناية",explore:"استكشفي المجموعة",eyebrow:"تصفحي حسب العلامة",brandTitle:"اختيار راقٍ من أشهر دور الأزياء العالمية.",brandCopy:"ابدئي من الصفحة الرئيسية، اختاري العلامة، وعودي هنا في أي وقت لتصفّح دار أخرى.",backHome:"العودة للرئيسية ←",footerLine:"حقائب فاخرة مختارة",inquire:"استفسار عبر واتساب",noProducts:"لا توجد منتجات منشورة تحت هذه العلامة بعد."}};
let lang = localStorage.getItem('ep_lang') || 'en';
let products = [];
const supabaseReady = cfg.SUPABASE_URL && cfg.SUPABASE_ANON_KEY && window.supabase;
const sb = supabaseReady ? window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY) : null;
function applyLinks(){['igLink','footerIg'].forEach(id=>document.getElementById(id).href=cfg.INSTAGRAM_URL||'#');['ttLink','footerTt'].forEach(id=>document.getElementById(id).href=cfg.TIKTOK_URL||'#');}
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=t[lang][el.dataset.i18n]||el.textContent});document.getElementById('langToggle').textContent=lang==='en'?'العربية':'English';}
function renderBrands(){const grid=document.getElementById('brandGrid');grid.innerHTML='';brands.forEach(b=>{const btn=document.createElement('button');btn.className='brandBtn';btn.type='button';btn.textContent=lang==='ar'?brandAr[b]:b;btn.onclick=()=>showBrand(b);grid.appendChild(btn);});}
function productImage(p){const first=Array.isArray(p.images)?p.images[0]:(typeof p.images==='string'?p.images.split('\n')[0]:'');return first?`<img src="${first}" alt="${p.name||'Product'}" onerror="this.remove()">`:'';}
function productCard(p){const name=lang==='ar'?(p.name_ar||p.name):(p.name||p.name_ar);const desc=lang==='ar'?(p.description_ar||p.description):(p.description||p.description_ar);const msg=encodeURIComponent(`Hello E&P, I would like to inquire about ${p.name || name}`);const wa=`https://wa.me/${cfg.WHATSAPP_NUMBER||'96555138907'}?text=${msg}`;return `<article class="productCard"><div class="gallery">${productImage(p)}<div class="placeholderBag"></div></div><div class="productInfo"><p class="eyebrow">${p.brand}</p><h3>${name||'Product'}</h3><div class="productMeta"><div>${p.price||'Upon request'}</div><div>${p.size||''}</div><p>${desc||''}</p></div><a class="waBtn" target="_blank" rel="noopener" href="${wa}">${t[lang].inquire}</a></div></article>`}
async function loadProducts(){if(sb){const {data,error}=await sb.from('products').select('*').order('created_at',{ascending:false});products = !error && data && data.length ? data : sampleProducts;}else{products = sampleProducts;}renderBrands();}
function showBrand(brand){document.getElementById('brands').classList.add('hidden');document.getElementById('brandView').classList.remove('hidden');document.getElementById('brandTitle').textContent=lang==='ar'?brandAr[brand]:brand;document.getElementById('brandEyebrow').textContent='Maison';const list=products.filter(p=>p.brand===brand);document.getElementById('productWrap').innerHTML=list.length?list.map(productCard).join(''):`<p class="muted">${t[lang].noProducts}</p>`;location.hash='brandView';}
document.getElementById('backHome').onclick=()=>{document.getElementById('brandView').classList.add('hidden');document.getElementById('brands').classList.remove('hidden');location.hash='brands'};
document.getElementById('langToggle').onclick=()=>{lang=lang==='en'?'ar':'en';localStorage.setItem('ep_lang',lang);applyLang();renderBrands();const visible=!document.getElementById('brandView').classList.contains('hidden');if(visible)document.getElementById('backHome').click();};
applyLinks();applyLang();loadProducts();
