const BRANDS=['Hermès','Dior','Chanel','Louis Vuitton','YSL','Prada','Fendi','Gucci','Balenciaga','Celine','Miu Miu','Bottega Veneta','Goyard','Burberry','Loewe'];
const SAMPLE={ 'Hermès':['Birkin 25','Kelly 28','Constance 18'], Dior:['Lady Dior Medium','Dior Toujours','Dior Book Tote'], Chanel:['Classic Flap','Coco Handle','Boy Bag'], 'Louis Vuitton':['Capucines','Neverfull MM','OnTheGo'], YSL:['Le 5 à 7','Loulou','Kate'], Prada:['Galleria','Re-Edition','Cleo'], Fendi:['Baguette','Peekaboo','Sunshine'], Gucci:['Jackie 1961','Diana','Marmont'], Balenciaga:['Rodeo','Hourglass','Le Cagole'], Celine:['Triomphe','Belt Bag','Ava'], 'Miu Miu':['Wander','Arcadie','Matelassé'], 'Bottega Veneta':['Andiamo','Jodie','Cassette'], Goyard:['Saint Louis','Anjou','Saigon'], Burberry:['Knight','Lola','Banner'], Loewe:['Puzzle','Hammock','Flamenco']};
const i18n={en:{home:'Home',admin:'Admin',tagline:'Curated Luxury Handbags',explore:'Explore Collection',brandIntro:'A curated selection from the world’s most celebrated maisons.',backHome:'← Back to Home',empty:'No products published under this brand yet.',wa:'Inquire via WhatsApp'},ar:{home:'الرئيسية',admin:'الإدارة',tagline:'حقائب فاخرة مختارة بعناية',explore:'استكشفي المجموعة',brandIntro:'اختيارات راقية من أشهر دور الأزياء العالمية.',backHome:'← العودة للرئيسية',empty:'لا توجد منتجات منشورة تحت هذه العلامة بعد.',wa:'استفسار عبر واتساب'}};
let lang='en';
const cfg=window.EP_CONFIG||{};const supabaseClient=window.supabase?.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
document.getElementById('instagramLink').href=cfg.instagramUrl;document.getElementById('tiktokLink').href=cfg.tiktokUrl;document.getElementById('footerInstagram').href=cfg.instagramUrl;document.getElementById('footerTiktok').href=cfg.tiktokUrl;
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=i18n[lang][el.dataset.i18n]||el.textContent});document.getElementById('langBtn').textContent=lang==='en'?'العربية':'English'}
document.getElementById('langBtn').onclick=()=>{lang=lang==='en'?'ar':'en';applyLang()};
function renderBrands(){const grid=document.getElementById('brandGrid');grid.innerHTML='';BRANDS.forEach(b=>{const btn=document.createElement('button');btn.className='brandBtn';btn.textContent=b;btn.onclick=()=>openBrand(b);grid.appendChild(btn)})}
async function openBrand(brand){document.getElementById('brandView').classList.remove('hidden');document.getElementById('brands').classList.add('hidden');document.getElementById('brandTitle').textContent=brand;window.location.hash='brandView';await renderProducts(brand)}
document.getElementById('backHome').onclick=()=>{document.getElementById('brandView').classList.add('hidden');document.getElementById('brands').classList.remove('hidden');location.hash='brands'};
async function getProducts(brand){try{if(!supabaseClient)return[];const {data,error}=await supabaseClient.from('products').select('*').eq('brand',brand).order('created_at',{ascending:false});if(error)throw error;return data||[]}catch(e){console.warn(e);return[]}}
async function renderProducts(brand){const wrap=document.getElementById('productsGrid');wrap.innerHTML='';let products=await getProducts(brand);if(!products.length){products=(SAMPLE[brand]||[]).map((name,i)=>({id:'sample-'+i,name,brand,price:'Inquire for price',description:'Example display item. Add real products from admin.',images:[],views:0}))}products.forEach(p=>{const img=Array.isArray(p.images)?p.images[0]:p.image_url;const msg=encodeURIComponent(`Hello, I would like to inquire about ${p.name} from ${p.brand}.`);const card=document.createElement('article');card.className='productCard';card.innerHTML=`<div class="productImg">${img?`<img src="${img}" alt="${p.name}">`:`<span>${brand[0]}</span>`}</div><h3>${p.name||'Unnamed product'}</h3><p>${p.price||''}</p><p>${p.size||''}</p><p>${lang==='ar'&&p.description_ar?p.description_ar:(p.description||'')}</p><a class="wa" target="_blank" rel="noreferrer" href="https://wa.me/${cfg.whatsappNumber}?text=${msg}">${i18n[lang].wa}</a>`;wrap.appendChild(card)})}
renderBrands();applyLang();
